Gusto/apollo-federation-ruby

- Gemfile.lock
- apollo-federation.gemspec
- lib/apollo-federation/any.rb
- spec/apollo-federation/any_spec.rb
Supersedes #12 to include tests
cc @tomasz-buchta @rylanc
> fix: Handle rails params in Any 

- .circleci/config.yml
This PR upgrades the CI config to use the newly-added `semantic-release-ruby` orb command.
> chore: upgrade orb and use semantic-release-ruby command

- README.md
On the graphql-ruby [roadmap](https://graphql-ruby.org/schema/class_based_api.html#roadmap), the `.define` API is marked for removal at `2.0` and sunsetted at `1.10` (which is the upcoming release). 
Hence just a small README change to clarify that we won't do any work to support the legacy API.
> docs: Clarify intent not to support legacy define API

- lib/apollo-federation/tracing.rb
👋 I am trying distributed tracing. No luck so far, but I have noticed a small but misleading typo in the exception message. Fixed that and made the exception more specific.
> fix: typo in exception message

- README.md
- lib/apollo-federation.rb
- lib/apollo-federation/federated_document_from_schema_definition.rb
- lib/apollo-federation/interface.rb
- lib/apollo-federation/object.rb
- lib/apollo-federation/schema.rb
- spec/apollo-federation/service_field_spec.rb
- spec/spec_helper.rb
Following the spec defined in: https://www.apollographql.com/docs/apollo-server/federation/federation-spec/
**Notes:**
`directive @extends on OBJECT | INTERFACE`
`directive @key(fields: _FieldSet!) on OBJECT | INTERFACE`
-> Introduce a new `ApolloFederation::Interface` module that can be included in base interface modules, using the API outlined in https://graphql-ruby.org/type_definitions/interfaces#definition-methods
`union _Entity`
Unions cannot reference interface types, so the resolver excludes non-object types to generate this field.
> feat: Support Interfaces

- lib/apollo-federation/tracing/node_map.rb
At this moment distributed tracing has an `active_support` runtime dependency. Which might not be welcome in some Ruby projects. 
It would be nice to leave it at least a development dependency or drop completely.
> fix: drop actionpack from runtime requirements

- yarn.lock
**Remediation**
Upgrade set-value to version 2.0.1 or later. For example:
set-value@^2.0.1:
version "2.0.1"
Always verify the validity and compatibility of suggestions with your codebase.
**Details**
CVE-2019-10747
high severity
Vulnerable versions: < 2.0.1
Patched version: 2.0.1
set-value is vulnerable to Prototype Pollution in versions before 2.0.1 and version 3.0.0. The function mixin-deep could be tricked into adding or modifying properties of Object.prototype using any of the constructor, prototype and proto payloads.
> chore(deps): Bump set-value to 2.0.1

- Gemfile.lock
- apollo-federation.gemspec
BREAKING CHANGE: Requires graphql ~> 1.9.8 and google-protobuf ~> 3.7
There is no version specified for the dependencies. This is unpleasant for those trying to integrate the gem with existing codebase. Even though the library is its early development stage it would be nice to at least specify requirements. Versions could be adjusted later on, but it's way easier to spot a problem that to see misleading `protobuf` errors.
> fix: specify dependency versions

- lib/apollo-federation/schema.rb
- lib/apollo-federation/service_field.rb
Recently, `graphql-ruby` started supporting visibility rules during SDL generation (PR: https://github.com/rmosolgo/graphql-ruby/pull/2637).  In order to utilize dynamic values set in the query context, it needs to be forwarded to `FederatedDocumentFromSchemaDefinition`.  Additionally, the current caching mechanism poses a problem if you have several gateways/clients with different visibility rules, so it has been removed.
> fix: Send context to SDL generation / don't cache

- lib/apollo-federation/schema.rb
- lib/apollo-federation/service_field.rb
- spec/apollo-federation/service_field_spec.rb
Methods definition here:
https://github.com/Gusto/apollo-federation-ruby/blob/master/lib/apollo-federation/schema.rb#L50
Currently we get an exception when running the service check command:
```
apollo schema:check --endpoint=http://localhost:3000/graphql ...
```
Results in:
```
unknown keyword: current_user
/Users/matt/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/apollo-federation-1.0.1/lib/apollo-federation/schema.rb:50:in `federation_sdl'
/Users/matt/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/apollo-federation-1.0.1/lib/apollo-federation/service_field.rb:13:in `_service'
/Users/matt/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.9.19/lib/graphql/schema/field.rb:652:in `public_send'
```
Our context
```
context = { current_user: current_user }
```
Changing this to a …
> fix: service field context

- lib/apollo-federation/tracing/tracer.rb
- spec/apollo-federation/tracing_spec.rb
Context can be on the query on passed directly as denoted by this statement. By without passing a second argument to `fetch`, it raises so we never get to the `data.fetch(:query).context` branch.
> fix: Make the tracer work with the new interpreter runtime

- Gemfile.lock
- apollo-federation.gemspec
- lib/apollo-federation/schema.rb
graphql-ruby 1.10.0 brought some breaking changes to its to_graphql method. See: https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#1100-20-jan-2020
> chore(deps): Allow for GraphQL dependencies >= 1.10.0

- spec/apollo-federation/tracing_spec.rb
Account for [breaking change](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#1100-20-jan-2020) to `graphql-ruby 1.10.0` in spec
> Class-based schemas using the interpreter must add use GraphQL::Analysis::AST to their schema (and update their custom analyzers, see https://graphql-ruby.org/queries/ast_analysis.html) #2363
> fix: Fix spec to account for breaking change to graphql-ruby 1.10.0

- lib/apollo-federation/entity_type_resolution_extension.rb
- spec/apollo-federation/entities_field_spec.rb
Hey!
Thanks for your work around this library.
When we are trying to implement authorization in our application we use exceptions and middleware, it works fine for everything except this gem, because the sync is being called [here](https://github.com/Gusto/apollo-federation-ruby/blob/master/lib/apollo-federation/entity_type_resolution_extension.rb#L7) which nullifies all data returned by `_entities` field even if the only one object is not authorized.
What we get without this patch:
```
{
"data": null,
"errors": [
{
"message": "Not authorized (Talent)",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"_entities"
],
"extensions": {
"code": "UNAUTHORIZED"
}
}
]
}
```
what we want to get: 
```
{
"data": {
"_entities": [
{
"id": "VjEtVGFsZW50LTEwMDAwMA",
"status": "active", …
```
> fix(lazy resolve): Handle problem with sync resolve

- graphql-1.9.gemfile.lock
Semantic release bot does not update the `graphql-1.9.gemfile.lock` file. 
https://github.com/Gusto/apollo-federation-ruby/commit/97cc246ed9b34a43aac94dd8bdf33dab5e8338c4#diff-e79a60dc6b85309ae70a6ea8261eaf95
> ci: Fix graphql-1.9.gemfile.lock

- graphql-1.9.gemfile.lock
- lib/apollo-federation/schema.rb
- lib/apollo-federation/service_field.rb
- spec/apollo-federation/entities_field_spec.rb
- spec/apollo-federation/service_field_spec.rb
The field was previously defined in the module making the
ApolloFederation::ServiceField the owner of the type instead of the
root Query.
> fix: Fix _service field type owner

- Appraisals
- gemfiles/graphql_1.10.gemfile
- gemfiles/graphql_1.10.gemfile.lock
- gemfiles/graphql_1.9.gemfile
- gemfiles/graphql_1.9.gemfile.lock
- lib/apollo-federation/service_field.rb
- spec/apollo-federation/service_field_spec.rb
This fixes a problem where `ApolloFederation::ServiceField#_service` passed a `context` of type `GraphQL::Query::Context` rather than `Hash` which violates the contract of [GraphQL::Language::DocumentFromSchemaDefinition#initialize](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/language/document_from_schema_definition.rb#L9). The API of `GraphQL::Query::Context` and `Hash` are similar enough that this didn't cause any problems until graphql-ruby 1.9.17 with the introduction of [context scoping](https://github.com/rmosolgo/graphql-ruby/pull/2634). After that change, calling `to_h`, `fetch` or `dig` on the context from anywhere in the resolution of `ApolloFederation::ServiceField#_service` (e.g. schema visibility checks) would result in a ` NoMethodError: undefined method …
> fix: Fix context passed to GraphQL::Schema.federation_sdl

- Gemfile.lock
- apollo-federation.gemspec
Hoping this will resolve #144 , where it seems like folks using M1 might have issue with the platform being forced to use the linux binary. Also updates bundler to the latest/greatest, which keeps turning up when you search for M1 compatibility issues, though not directly related to this one. 
Hopefully the bundler update accounts for the fact there are multiple mac platform types better. 
This platform change was introduced by semantic release bot in https://github.com/Gusto/apollo-federation-ruby/commit/631ebfe4bf4fb2d4097f6322be321b8814755234#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fR44 which could be a bundler bug :shrug:
> feat: Remove erronous? lock to x86_64-linux

- release.config.js
main is not included in its list of default branches
> chore: configure semantic release for main branch

- Gemfile.lock
- apollo-federation.gemspec
- gemfiles/graphql_1.10.gemfile.lock
- gemfiles/graphql_1.11.gemfile.lock
- gemfiles/graphql_1.12.gemfile.lock
1. In https://github.com/Gusto/apollo-federation-ruby/pull/150, the intention was to remove the platform lock. In that PR, `google-protobuf` was locked to `3.13.x` as per the gemspec and specs. 
2. However in reality, consumers could have been installing `3.19.x` which I think is very common. We should relax the lock to minor version which lets people bump to the latest minor version. 
3. But I've also bumped the requirement to `~> 3.19` because of this [CVE](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22569) 
This should result in a bump to `2.1.0` and that should be alright because of point 2 and if you're locked to below protobuf `3.19`, the major release should guard that
> fix: Bump protobuf to 3.19 and lock on minor version

- .circleci/config.yml
Not gonna lie, 50% of the motivation of the PR is to trigger a release 😸 . In the previous one, the `fix` message was in the PR title but not in the commit, which I think doesn't trigger a release. 
Since our ruby image is really old, I thought it's at least a good task to upgrade it to the latest of the 2.6 series.
https://circleci.com/developer/images/image/cimg/ruby
> fix: Update to latest CircleCI Ruby 2.6.x image

- .circleci/config.yml
The main build [failed](https://app.circleci.com/pipelines/github/Gusto/apollo-federation-ruby/469/workflows/a0756cc1-5622-46e8-b7af-bf4979f6cb70/jobs/2532) . Guessing it's the cache version. 
This PR bumps the cache version manually. 
PRs like this pollute the history, especially when the problem is temporary, if the cache gets invalidated (15 days?), the build would have passed. Let's investigate if we can: 
1. Also base the cache on the image version 
2. And have a manual bump control that's based on an ENV variable 
Will open an issue for it if it's indeed a cache issue.
> build: Bump cache version to fix failing main build

- Gemfile.lock
- gemfiles/graphql_1.11.gemfile.lock
- release.config.js
This is a stopgap solution to #169.
When we run `appraisal install`, it does a `bundle check || bundle install`. This is probably an optimization to avoid bundling if our local gems satisfy the needed dependencies. 
However, there seems to be some issue with `bundle check` that's causing it to alter our `gemfiles` to a platform specific version. See the Rubygems issue in #169. 
For now, let's use `bundle install` so this doesn't happen. 
**Self note: REMEMBER to prefix commit to cut a fix release**
> fix: Use `bundle install` to avoid `bundle check` that changes our lockfiles

- .circleci/config.yml
- Gemfile.lock
Last attempt to see if this fixes the platform locking issue when semantic bot commits. 
Everytime we release an update with `fix`, it adds to the changelog :( 
Was hoping the fix would help confirm the issue for https://github.com/rubygems/rubygems/issues/5325 too.  If this doesn't work, I'll wait for the issue and also figure out how to run semantic bot locally or on Circle without publishing for debugging.
> fix: Attempt to remove platform specific lock on google-protobuf

- README.md
- example/accounts.rb
- example/inventory.rb
- example/products.rb
- example/reviews.rb
- lib/apollo-federation/field.rb
- lib/apollo-federation/field_set_serializer.rb
- lib/apollo-federation/interface.rb
- lib/apollo-federation/object.rb
- spec/apollo-federation/entities_field_spec.rb
- spec/apollo-federation/field_set_serializer_spec.rb
- spec/apollo-federation/service_field_spec.rb
This is an awesome library but one of the things I initially found confusing was the naming differences between graphql-ruby fields (snake case symbols) and apollo-federation-ruby field references (lower camelcase) e.g.
```ruby
class Order < BaseObject
field :zip_code, String, null: true, external: true
field :weight, Int, null: true, external: true
field :shipping_estimate, Int, null: true, requires: { fields: 'zipCode weight' }
end
```
This PR updates field set arguments to be either strings which follow the Apollo syntax or arrays, hashes and snake case symbols that follow the graphql-ruby conventions e.g.
```ruby
class Order < BaseObject
field :zip_code, String, null: true, external: true
field :weight, Int, null: true, external: true
field :shipping_estimate, Int, null: true, …
```
> feat: Snake case field references

- gemfiles/graphql_2.0.gemfile.lock
- lib/apollo-federation/federated_document_from_schema_definition.rb
`InstanceDefinable` is used for the old block based `define` syntax. It's been deprecated since `1.10`. Not sure why we're referencing it. 
https://github.com/rmosolgo/graphql-ruby/pull/2680
> fix: remove InstanceDefinable reference

- Gemfile.lock
Reverts Gusto/apollo-federation-ruby#188
Just in case we cannot fix forward.
> chore: revert add linux and darwin platforms to lockfile

- lib/apollo-federation/field.rb
- lib/apollo-federation/field_set_serializer.rb
- lib/apollo-federation/interface.rb
- lib/apollo-federation/object.rb
- spec/apollo-federation/field_set_serializer_spec.rb
- spec/apollo-federation/service_field_spec.rb
Followup to a previous feature release, which intentionally did not camelize string inputs in order to preserve backwards compatibility. Here we are breaking compatibility to make the behavior consistent. Users can revert the behavior using the `camelize` option if it is necessary.
BREAKING CHANGE: string fields will be camelized by default rather than passed as is.
> fix: camelize string fields to match sym behavior

- .gitignore
- lib/apollo-federation/entities_field.rb
- spec/apollo-federation/entities_field_spec.rb
This addresses the issues with using data loader in the existing `resolve_reference` method. (See: #205) 
By grouping all the references of the same type into a single call to `resolve_references` the records can more easily be loaded as a batch. This can be done using a data loader (`.load_all`) or just a direct DB query as all the references are provided in a single method call. 
The existing `resolve_reference` method is still supported but `resolve_references` will be the preferred approach.
> feat: introduce optional `resolve_references` method

- lib/apollo-federation/object.rb
- lib/apollo-federation/schema.rb
- spec/apollo-federation/schema_spec.rb
- spec/apollo-federation/service_field_v2_spec.rb
The Apollo team are working on a new release for the Federation spec. This release will bump the spec to `v2.3` and one of the main features is the support for referencing Entities that are interfaces. You can read more about this [here](https://github.com/apollographql/federation/issues/2277), and check the initial implementation [here](https://github.com/apollographql/federation/pull/2279). 
In this PR I'm addressing two minor things:
* Adds support for the `@interfaceObject` for the `Object` class
* Adds support to link the latest version of `v2.3`
* Fixes the custom namespace not being added to the SDL. (eg: `@link(url: "https://specs.apollo.dev/federation/v2.3", as: "fed2")`)
* We need to add a validation check in `v2.3` is that we can't apply `@key` directive on interfaces for …
> feat: adds support for the `@interfaceObject` directive

- lib/apollo-federation/federated_document_from_schema_definition.rb
- lib/apollo-federation/schema.rb
- spec/apollo-federation/service_field_v2_spec.rb
Currently, due to different namespaces across multiple subgraphs, we are getting the following error:
```GraphQL
LINK_IMPORT_NAME_MISMATCH: The federation "@inaccessible" directive is imported with mismatched name between subgraphs: it is imported as "@federation__inaccessible" in subgraphs "A" and "B" but "@inaccessible" in subgraphs "C", "D"...
```
According to [prasek](https://github.com/prasek)'s comment [here](https://github.com/apollographql/federation/issues/1976#issuecomment-1184522540), we should always import the `@inaccessible` directive to avoid multiple namespaces. This PR address this.
> fix: import `@inaccessible` directive in Fed v2.3

- lib/apollo-federation/has_directives.rb
- lib/apollo-federation/schema.rb
- spec/apollo-federation/service_field_v1_spec.rb
- spec/apollo-federation/service_field_v2_spec.rb
This PR adds inheritance of federation directives for consistency with graphql-ruby's native directives and other parts of their API like `field`, `field_class`, etc. Code like this is now supported:
```ruby
class RemotelyReferenceableObject < SalsifyGraphQL::Server::BaseObject
key fields: 'id'
field :id, ID, null: false
end
class BlogType < RemotelyReferenceableObject
field :text, String, null: false
end
class BaseSchema <  GraphQL::Schema
include ApolloFederation::Schema
federation version: '2.0'
end
class MySchema < BaseSchema
end
```
> fix: Inherit federation directives

- release.config.js
- Sets semantic release bundle command to a plain ol' `bundle install`
> ci: fix release by only running bundle install w/o appraisal during publish

- Gemfile.lock
- apollo-federation.gemspec
- Updates `google-protobuf` to 3.22.x, which supports Ruby 3.2
Co-authored-by @such
Closes https://github.com/Gusto/apollo-federation-ruby/pull/231
> chore: update google-protobuf to 3.22.x

- lib/apollo-federation/entities_field.rb
- spec/apollo-federation/entities_field_spec.rb
Hello!
I ran into this bug a couple weeks ago. It took me a little while to find the cause of this fix, but this seems to be working well for us.
The first commit is a stylistic change—I'm happy to revert it. The second commit demonstrates the failing case, and the last fixes it. I wrote a detailed description of the change in the final commit as well.
I do know that this solution is a little less efficient than the previous version. Theoretically, if there is a request asking for _N_ entities of `[TypeA, TypeB, TypeA, TypeB, TypeA, TypeB, ...]`, this would result in _N_ calls to `resolve_references`.
I'm quite sure that it would be possible to make this almost as efficient as before (I mean, 1 call to `resolve_references` per distinct type). However, I'd like to consider that out of …
> fix: ensure correct ordering of `resolve_references`

- lib/apollo-federation/schema.rb
- spec/apollo-federation/service_field_v1_spec.rb
- spec/apollo-federation/service_field_v2_spec.rb
This PR fixes `ApolloFederation::Schema` to properly inherit the `Query` type from any superclasses so code like the following works as expected:
```ruby
class BaseSchema < GraphQL::Schema
include ApolloFederation::Schema
query QueryType
end
class MySchema < BaseSchema
end
```
We use this subclassing pattern quite a bit in tests to avoid mutating our "real" schema class.
> fix: inherit Query type from schema superclass

- lib/apollo-federation/tracing/tracer.rb
- spec/apollo-federation/tracing_spec.rb
Fixes https://github.com/Gusto/apollo-federation-ruby/issues/197
We found that once we implemented tracing, multiplex queries would fail with only a `NoMethodError (undefined method 'context' for nil:NilClass)`
In debugging I found that multiplex queries end up hitting `Tracer.execute_query_lazy` which was expecting a single query at `data[:query]`, which was `nil` when `data[:multiplex].queries` included more than one query. 
This PR adds support for either a single query or several queries as in a multiplex context.
> fix(tracer): add support for multiplex

- README.md
- example/accounts.rb
- example/gateway.js
- example/graphql_server.rb
- example/inventory.rb
- example/products.rb
- example/reviews.rb
- lib/apollo-federation/tracing.rb
- package.json
- spec/integration/integration.test.js
- yarn.lock
This PR fixes `ApolloFederation::Tracing.should_add_traces` to look for the correct Apollo tracing headers. The Apollo Router/Apollo Gateway sends the header as `apollo-federation-include-trace` but [Rack](https://github.com/rack/rack/blob/main/SPEC.rdoc) follows the [CGI spec](https://www.rfc-editor.org/rfc/rfc3875#section-4.1.18) and converts it to `HTTP_APOLLO_FEDERATION_INCLUDE_TRACE`. I also updated the README to read the headers from `request.headers` rather than `headers` since `headers` are the response headers in Rails controllers.
I had to upgrade to a more recent version of Apollo Server/Apollo Gateway to actually get integration tests working for this. Hopefully that's ok!
> fix: ApolloFederation::Tracing.should_add_traces() looks for correct headers

- lib/apollo-federation/schema.rb
- spec/apollo-federation/entities_field_spec.rb
This fixes the generated `_Entity` union to include members inherited from a schema superclass. I missed this in the original fix for #241.
> fix: include inherited types in generated _Entity union

- lib/apollo-federation/federated_document_from_schema_definition.rb
- lib/apollo-federation/schema.rb
- spec/apollo-federation/service_field_v2_spec.rb
This PR fixes two visibility scenarios that graphql-ruby supports but apollo-federation-ruby's does not:
1. Multiple object types with the same name as long as only one is visible at runtime
2. Multiple fields with the same name as long as only one is visible at runtime
The first scenario was broken because visibility checking in [GraphQL::Schema.types](https://github.com/rmosolgo/graphql-ruby/blob/3a548f8cb540f16f09506bde9fc0778d3eba276d/lib/graphql/schema.rb#L286) was applied when generating the `_Entity` union but we don't have a properly setup context at this point, resulting in either a `GraphQL::Schema::DuplicateNamesError` or a `NoMethodError: undefined method 'introspection?' for nil:NilClass` depending on how an application has setup their visibility checks for types with the …
> fix: visibility checks should handle duplicate types and fields

- CHANGELOG.md
This adds information to v3.4.0 highlighting the breaking change to composition discussed in Gusto/apollo-federation-ruby#221 and providing guidance on how to proceed.
> docs(changelog): add breaking change to 3.4.0

- lib/apollo-federation/schema.rb
- spec/apollo-federation/schema_spec.rb
The way we override the `Schema#query` method makes it so that we don't call `add_type_and_traverse` when setting the new query type like graphql-ruby does [here](https://github.com/rmosolgo/graphql-ruby/blob/5eac86139138332d17d4eb5ea3f59ae8e0aa8cfb/lib/graphql/schema.rb#L416). Currently we only add and traverse the query type when accessing the query.
The following script demonstrates this:
```ruby
require 'bundler/inline'
gemfile do
source 'https://rubygems.org'
gem 'apollo-federation'
end
class CatType < GraphQL::Schema::Object
end
class QueryType < GraphQL::Schema::Object
field :cat, CatType, null: false
end
class Schema < GraphQL::Schema
include ApolloFederation::Schema
query QueryType
end
p Schema.get_type('Cat')
#=> nil
```
This PR makes it so that we call …
> fix: ensure query object is traversed

- README.md
Needed the correct semantic version name for https://github.com/Gusto/apollo-federation-ruby/pull/282
Need to add a CI check for that.
> fix: graphql-ruby 2.3 compatibility
